#!/usr/bin/env python3
"""
Generate Homebrew formula resource stanzas for Claude MPM dependencies.

This script fetches package information from PyPI and generates the Ruby
resource blocks needed for the Homebrew formula.
"""

import json
import urllib.request
import urllib.error
import sys
from typing import Dict, Set, List, Tuple


def fetch_pypi_info(package_name: str, version: str = None) -> Dict:
    """Fetch package information from PyPI."""
    if version:
        url = f"https://pypi.org/pypi/{package_name}/{version}/json"
    else:
        url = f"https://pypi.org/pypi/{package_name}/json"

    try:
        with urllib.request.urlopen(url) as response:
            return json.loads(response.read())
    except urllib.error.HTTPError as e:
        print(f"Error fetching {package_name}: {e}", file=sys.stderr)
        return None


def get_source_url_and_sha256(package_info: Dict) -> Tuple[str, str]:
    """Extract source distribution URL and SHA256 from package info."""
    urls = package_info.get("urls", [])

    # Prefer source distribution
    for url_info in urls:
        if url_info["packagetype"] == "sdist":
            return url_info["url"], url_info["digests"]["sha256"]

    # Fallback to wheel if no source dist
    for url_info in urls:
        if url_info["packagetype"] == "bdist_wheel":
            return url_info["url"], url_info["digests"]["sha256"]

    return None, None


def generate_resource_stanza(package_name: str, version: str = None) -> str:
    """Generate a Homebrew resource stanza for a package."""
    info = fetch_pypi_info(package_name, version)
    if not info:
        return f'  # ERROR: Could not fetch info for {package_name}'

    actual_version = info["info"]["version"]
    url, sha256 = get_source_url_and_sha256(info)

    if not url or not sha256:
        return f'  # ERROR: No source distribution found for {package_name}'

    # Normalize package name for resource (replace underscores/hyphens)
    resource_name = package_name.lower().replace("_", "-")

    stanza = f'''  resource "{resource_name}" do
    url "{url}"
    sha256 "{sha256}"
  end'''

    return stanza


def get_claude_mpm_dependencies() -> List[str]:
    """Get the list of direct dependencies for Claude MPM."""
    # Fetch claude-mpm package info
    info = fetch_pypi_info("claude-mpm", "4.22.2")
    if not info:
        print("Error: Could not fetch claude-mpm info", file=sys.stderr)
        return []

    requires_dist = info["info"].get("requires_dist", [])
    if not requires_dist:
        print("Warning: No requires_dist found", file=sys.stderr)
        return []

    # Parse dependencies (strip version specifiers and extras)
    dependencies = []
    for req in requires_dist:
        # Skip extra dependencies and development dependencies
        if "extra ==" in req:
            continue

        # Extract package name - remove version specifiers (<, >, =, !=, ~=, etc.)
        pkg_name = req.split(";")[0].split("[")[0].strip()
        # Remove all comparison operators and version numbers
        for op in [">=", "<=", "==", "!=", "~=", ">", "<"]:
            if op in pkg_name:
                pkg_name = pkg_name.split(op)[0].strip()
                break

        if pkg_name and pkg_name not in dependencies:
            dependencies.append(pkg_name)

    return sorted(dependencies)


def main():
    """Generate all resource stanzas for Claude MPM dependencies."""
    print("# Homebrew Formula Resources for Claude MPM")
    print("# Generated by scripts/generate_resources.py")
    print()

    # Core dependencies for Claude MPM
    dependencies = get_claude_mpm_dependencies()

    if not dependencies:
        # Fallback to known dependencies if auto-detection fails
        print("# Using fallback dependency list", file=sys.stderr)
        dependencies = [
            "anthropic",
            "click",
            "pyyaml",
            "rich",
            "jinja2",
            "pydantic",
            "python-dotenv",
            "flask",
            "flask-cors",
            "flask-socketio",
            "python-socketio",
            "gitpython",
            "psutil",
            "questionary",
            "tiktoken",
            "prompt-toolkit",
            "pyperclip",
            "pygments",
            "distro",
            "packaging",
            "setuptools",
            "requests",
            "aiofiles",
            "dataclasses-json",
            "marshmallow",
            "marshmallow-enum",
            "mypy-extensions",
            "typing-inspect",
            "typing-extensions",
        ]

    print(f"# Generating resources for {len(dependencies)} dependencies...")
    print()

    for package in dependencies:
        print(f"Generating resource for {package}...", file=sys.stderr)
        stanza = generate_resource_stanza(package)
        print(stanza)
        print()

    print("# Resource generation complete!")


if __name__ == "__main__":
    main()
